FROM node:7.10.0
MAINTAINER kaiyadavenport@gmail.com
WORKDIR /app/frontend
COPY ./frontend/package.json /app/frontend/package.json
RUN npm install
COPY ./frontend /app/frontend
ENTRYPOINT ["npm", "run"]
CMD ["watch"]