FROM binocarlos/yarn-base
MAINTAINER kaiyadavenport@gmail.com
WORKDIR /app/api
COPY ./template-api /app/template-api
COPY ./api/package.json /app/api/package.json
COPY ./api/yarn.lock /app/api/yarn.lock
RUN yarn install
COPY ./api /app/api
ENTRYPOINT ["node", "src/index.js"]