version: '2'
services:
  postgres:
    image: postgres:9.6.1
    container_name: bookingdev_postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    env_file: env.dev
  redis:
    image: redis
    container_name: bookingdev_redis
    volumes:
      - ./.data/redis:/data
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    container_name: bookingdev_frontend
    depends_on:
      - api
    links:
      - api:api
    entrypoint:
      - "bash"
      - "run.sh"
    environment:
      - MANUALRUN
      - NODE_ENV=development
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    container_name: bookingdev_api
    entrypoint:
      - "bash"
      - "run.sh"
    env_file: env.dev
    environment:
      - MANUALRUN
      - NODE_ENV=development
    