apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: farmbooking-api
        image: gcr.io/webkit-servers/farmbooking-api:${GITHASH}
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
        - name: REDIS_SERVICE_HOST
          value: redis.${NAMESPACE}.svc.cluster.local
        - name: POSTGRES_SERVICE_HOST
          value: postgres.postgres.svc.cluster.local
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: POSTGRES_PASSWORD
        - name: USE_INSTALLATION
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: USE_INSTALLATION
        - name: CONFIG_FOLDER
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: CONFIG_FOLDER
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: COOKIE_SECRET
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: ADMIN_PASSWORD
        - name: STRIPE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: STRIPE_PUBLIC_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: STRIPE_SECRET_KEY
        - name: MAILGUN_API_KEY
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: MAILGUN_API_KEY
        - name: MAILGUN_DOMAIN
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: MAILGUN_DOMAIN
        - name: TWILIO_SID
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: TWILIO_SID
        - name: TWILIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: appsecrets
              key: TWILIO_TOKEN
