const icons = {
  dashboard: 'dashboard',
  help: 'help_outline',
  about: 'info_outline',
  home: 'home',
  item: 'label',
  menu: 'menu',
  options: 'more_vert',
  logout: 'exit_to_app',
  login: 'account_circle',
  register: 'create',
  cancel: 'clear',
  revert: 'undo',
  save: 'send',
  add: 'add',
  edit: 'create',
  project: 'layers',
  delete: 'delete',
  folder_open: 'keyboard_arrow_right',
  view: 'visibility',
  actions: 'more_vert',
  folder: 'folder',
  folderadd: 'create_new_folder',
  folderopen: 'folder_open',
  settings: 'settings',
  search: 'search',
  users: 'people',
  video: 'videocam',
  back: 'arrow_back',
  forward: 'arrow_forward',
  time: 'access_time',
  star: 'star',
  disk: 'storage',
  root: 'apps',
  up: 'arrow_upward',
  bookingForm: 'event',
  template: 'receipt',
  booking: 'date_range',
  calendar: 'date_range',
  schedule: 'dns',
  phone: 'settings_phone',
  web: 'web',
  date_range: 'date_range',
  slot: 'access_time',
  makeBooking: 'arrow_forward',
  pdf: 'picture_as_pdf',
}

const config = {  
  api: '/api/v1',  
  icons
}

export default config