FROM binocarlos/yarn-base
MAINTAINER kaiyadavenport@gmail.com
WORKDIR /app/api
COPY ./api/package.json /app/api/package.json
COPY ./api/yarn.lock /app/api/yarn.lock
COPY ./shared /app/shared
RUN yarn install
COPY ./api /app/api
COPY ./frontend/dist /wwwdata
ENTRYPOINT ["npm", "run"]
CMD ["serve"]